services:
  vaultwarden-backup:
    image: bruceforce/vaultwarden-backup:latest
    container_name: vaultwarden-backup
    hostname: vaultwarden-backup
    restart: always
    init: true
    depends_on:
      - vaultwarden
    volumes:
      - ./vaultwarden-data/:/data/
      - /media/rclone/vaultwarden-backup:/backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TIMESTAMP=true
      - DELETE_AFTER=10
      - UID=0
      - GID=1000
      - TZ=Asia/Kolkata
      - BACKUP_DIR=/backup
      - CRON_TIME=0 0 * * * # see https://crontab.guru/, define without quotes!

  vaultwarden:
    # image is pinned because of the warning of data loss.
    # MAKE A BACKUP BEFORE MIGRATING TO ANOTHER VERSION!!!!
    image: vaultwarden/server:1.34.1-alpine 
    container_name: vaultwarden
    restart: unless-stopped
    # ports:
    #   - "80:80"
    networks:
      vaultwarden_subnet:
        ipv4_address: "172.255.8.2"
    environment:
      - DOMAIN=https://vaultwarden.jeelpa.tel
    volumes:
      - ./vaultwarden-data/:/data/
  
  caddy:
    build: 
      context: .
      dockerfile: ./Dockerfile.caddy
    
    restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./certs/:/certs/
      - ./caddy/data:/data
      - ./caddy/config:/config

    env_file: .env

    networks:
      vaultwarden_subnet:
        ipv4_address: "172.255.8.3"

networks:
  vaultwarden_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.255.8.0/24
          gateway: 172.255.8.1
