services:
  vaultwarden:
    # image is pinned because of the warning of data loss.
    # MAKE A BACKUP BEFORE MIGRATING TO ANOTHER VERSION!!!!
    image: vaultwarden/server:1.34.1-alpine 
    container_name: vaultwarden
    restart: unless-stopped
    # ports:
    #   - "80:80"
    networks:
      vaultwarden_subnet:
        ipv4_address: "172.255.8.2"
    environment:
      - DOMAIN=https://vaultwarden.jeelpa.tel
    volumes:
      - ./vaultwarden-data/:/data/
  
  caddy:
    build: 
      context: .
      dockerfile: ./Dockerfile.caddy
    
    restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./certs/:/certs/
      - ./caddy/data:/data
      - ./caddy/config:/config

    env_file: .env

    networks:
      vaultwarden_subnet:
        ipv4_address: "172.255.8.3"

networks:
  vaultwarden_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.255.8.0/24
          gateway: 172.255.8.1
