services:
        # flaresolverr:
        #   image: ghcr.io/flaresolverr/flaresolverr:latest
        #   container_name: flaresolverr
        #   environment:
        #     - LOG_LEVEL=${LOG_LEVEL:-info}
        #     - LOG_HTML=${LOG_HTML:-false}
        #     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
        #   networks:
        #     media_server_subnet:
        #       ipv4_address: "172.255.2.9"
        #   ports:
        #     - "${PORT:-8191}:8191"
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./prowlarr/data:/config
    networks:
      media_server_subnet:
        ipv4_address: "172.255.2.8"
    # ports:
    #   - 9696:9696
  
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - WEBUI_PORT=80
    # ports:
    #   - 8090:80
    networks:
      media_server_subnet:
        ipv4_address: "172.255.2.7"
    volumes:
      - ./qbittorrent/config:/config
      - ./data/torrents:/data/torrents

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./bazarr/config:/config
      - ./data:/data
    networks:
      media_server_subnet:
        ipv4_address: "172.255.2.6"
    # ports:
    #   - 6767:6767
  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./radarr/data:/config
      - ./data:/data
    networks:
      media_server_subnet:
        ipv4_address: "172.255.2.5"
    # ports:
    #   - 7878:7878
  
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./lidarr/config:/config
      - ./data:/data
    networks:
      media_server_subnet:
        ipv4_address: "172.255.2.4"
    # ports:
    #   - 8686:8686
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      media_server_subnet:
        ipv4_address: "172.255.2.3"
    volumes:
      - ./sonarr/data:/config
      - ./data:/data
  #   ports:
  #     - 8989:8989

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "jellyfin"
    
    networks:
      media_server_subnet:
        ipv4_address: "172.255.2.2"
    # ports:
    #   - 8096:8096
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./data/media:/media


networks:
  media_server_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.255.2.0/24
          gateway: 172.255.2.1
