services:
  syncthing:
    image: syncthing/syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./syncthing:/var/syncthing
   #ports:
   #  - 8384:8384 # Web UI
   #  - 22000:22000/tcp # TCP file transfers
   #  - 22000:22000/udp # QUIC file transfers
   #  - 21027:21027/udp # Receive local discovery broadcasts

    networks:
      syncthing_subnet:
        ipv4_address: "172.255.4.2"
    
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "syncthing"

    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  syncthing_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.255.4.0/24
          gateway: 172.255.4.1

