services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    env_file: ".env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./config:/config
    restart: unless-stopped
